name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  who-not-to-greet:
    description: 'Who not to greet'
    required: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
  who-to-dislike:
    description: 'Who we dislike'
runs:
  using: 'node20'
  main: 'index.js'
